name: Translate Plugin
Description: 'Action to translate a Jeedom Plugin'

inputs:
  source_language:
    description: 'source language for translations, must be one of the following value: "fr_FR | en_US | es_ES | de_DE"'
    type: string
    required: false
    default: 'fr_FR'
  deepl_api_key:
    description: 'deepl API KEY for automatic translation'
    type: string
    required: false
    default: ''
  include_empty_translation:
    description: 'prompts without translation will be included in language files if true'
    type: boolean
    required: false
    default: false
  use_core_translations:
    description: 'If true, tool will use translations from Jeedom core for missing plugin translations'
    type: boolean
    required: false
    default: true
  generate_source_language_translations:
    description: 'If true, the translation file corresponding to the source language will be generated (which is useless)'
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    # Checks-out plugin repository under $GITHUB_WORKSPACE
    - name: "Checkout plugin files"
      uses: actions/checkout@v4
      with:
        path: 'plugin'

    - name: "Checkout jeedom/core for default translations"
      uses: actions/checkout@v4
      with:
        repository: 'jeedom/core'
        ref: 'alpha'
        path: 'jeedom_core'

    - name: "Setup python 3.12"
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: "Generate translations..."
      shell: bash
      env:
        source_language: ${{ inputs.source_language }}
        deepl_api_key: ${{ inputs.deepl_api_key }}
        include_empty_translation: ${{ inputs.include_empty_translation }}
        use_core_translations: ${{ inputs.use_core_translations }}
        generate_source_language_translations: ${{ inputs.generate_source_language_translations }}
      run: |
        python ${{ github.action_path }}/src/translate_plugin.py

    - name: "Create Pull Request to plugin..."
      uses: peter-evans/create-pull-request@v6
      with:
        path: 'plugin'
        branch: translations
        delete-branch: true
        add-paths: |
          core/i18n/*.json
          plugin_info/info.json
        title: "Update translations"
        body: "Automated translations done by [Mips2648/plugins-translations workflow](https://github.com/Mips2648/plugins-translations)"
        commit-message: "Auto update translation done by Mips2648/plugins-translations workflow"

branding:
  icon: 'globe'
  color: 'orange'
